### ISSUE TITLE
Unable to launch UI using Mac OS

### ISSUE THREAD

**Issue by pranavonline** [CognizantQAHub/Cognizant-Intelligent-Test-Scripter#118]
Hello Team,

I am getting the error ""UI:MainUI" java.lang.ExceptionInInitializerError" while launching the UI.

Steps:
- Downloaded cognizant-intelligent-test-scripter-*-setup.zip
- Added extension to Chrome
- Install Extension certificate

Error is occurring after creating sikuli folder
~/Library/Application Support/Sikulix/SikulixTesseract/tessdata

Try to launch UI. While launching UI error on console and UI is not launched

2019-05-03 10:19:02:05S -0500 [INFO] com.cognizant.cognizantits.ide.main.Main main:Launching Cognizant Intelligent Test Scripter IDE
2019-05-03 10:19:04:05S -0500 [INFO] com.cognizant.cognizantits.engine.support.reflect.ClassFinder checkJarFile:Finding Commands in /Users/pranavgupta/Downloads/cognizant-intelligent-test-scripter-1.2/lib/cognizant-intelligent-test-scripter-engine-1.2.jar
2019-05-03 10:19:07:05S -0500 [INFO] com.cognizant.cognizantits.engine.drivers.ChromeEmulators load:Loading ChromeEmulators from file
Exception in thread "UI:MainUI" java.lang.ExceptionInInitializerError
	at com.cognizant.cognizantits.ide.main.shr.image.SikuliSettings.init(SikuliSettings.java:28)
	at com.cognizant.cognizantits.ide.main.shr.image.ImageSpy.<init>(ImageSpy.java:62)
	at com.cognizant.cognizantits.ide.main.shr.SHR.<init>(SHR.java:44)
	at com.cognizant.cognizantits.ide.main.mainui.AppMainFrame.<init>(AppMainFrame.java:111)
	at com.cognizant.cognizantits.ide.main.Main.lambda$launchUI$0(Main.java:85)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.NumberFormatException: For input string: "."
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:638)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at org.sikuli.basics.Settings.<clinit>(Settings.java:123)
	... 6 more

**Comment by Shantha93** [comment]
Please refer the a query on the same here,
https://groups.google.com/forum/#!topic/cognizant-intelligent-test-scripter/Ki-ji99rWiw

**Comment by pranavonline** [comment]
I am still getting the same issue.
Seems the framework is not supporting the Mac machine.
I already did as per below mentioned comments due to that UI start launching but not launched completely due to Exception in thread "UI:MainUI" java.lang.ExceptionInInitializerError as mentioned in main issue.
"Open terminal in the location where you have the tool (Cognizant Intelligent Test scripter) installed and execute the "Run.command" file after giving the necessary permission through "chmod" command as given in the installation document"

**Comment by Shantha93** [comment]
CITS current version supports only java 8. Hence please use only this java version for CITS. Install java and update the path in mac to point to this java version.

**Comment by pranavonline** [comment]
Thanks for support.

I tried but hard luck. :(
Is there any way I can disable sikuli and execute the framework? Current application has no requirement of sikuli.
Any settings or properties?

**Comment by Shantha93** [comment]
Please type java -version in the terminal and share us the results and try in normal jdk not in open jdk for mac.
