### ISSUE TITLE
Unable to load CITS MacOS

### ISSUE THREAD

**Issue by sikemausa** [CognizantQAHub/Cognizant-Intelligent-Test-Scripter#134]
**I'm submitting a ...**

[x] support request

**Current behavior**
CITS will not start, and gives the following error when trying to run Run.command on MacOS. Please advise.

`Exception in thread "UI:MainUI" java.lang.NoClassDefFoundError: javafx/embed/swing/JFXPanel
	at com.cognizant.cognizantits.ide.util.browser.PlatformBrowser.getBrowser(PlatformBrowser.java:21)
	at com.cognizant.cognizantits.ide.main.mainui.components.DashBoard.load(DashBoard.java:56)
	at com.cognizant.cognizantits.ide.main.mainui.AppMainFrame.init(AppMainFrame.java:136)
	at com.cognizant.cognizantits.ide.main.mainui.AppMainFrame.<init>(AppMainFrame.java:118)
	at com.cognizant.cognizantits.ide.main.Main.lambda$launchUI$0(Main.java:85)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: javafx.embed.swing.JFXPanel
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 6 more`

* **OS :** 
MacOS 10.14.5

* **JAVA :** 
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_222-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.222-b10, mixed mode)

* **Browser | Driver  :** 
Chrome 77

**Comment by Shantha93** [comment]
Not an issue, please find your query answered here,
https://groups.google.com/forum/#!topic/cognizant-intelligent-test-scripter/cN5C0W4DRS8
