### ISSUE TITLE
Unable to execute mobile native applications in Android devices

### ISSUE THREAD

**Issue by Shantha93** [CognizantQAHub/Cognizant-Intelligent-Test-Scripter#49]
[x] Bug Report

Environment:

- Appium Desktop latest: 1.6.4

- Android

- Windows

Bug Details:

I tried to execute mobile native (Android) applications in CITS, as soon as the application launches, instead of executing the first step in the script, the session always closes with an error message below,

```
2017-07-14 16:15:47:07S +0530 [INFO] org.openqa.selenium.remote.ProtocolHandshake createSession:Detected dialect: OSS
test Launched
Step:1   | Object: 8 | Action: assertElementDisplayed | Input:  | Conditon:  | @14-Jul-2017 16:16:35.035
2017-07-14 16:16:35:07S +0530 [SEVERE] com.cognizant.cognizantits.engine.core.Task runIteration:Driver test Closed / Could not be reached
com.cognizant.cognizantits.engine.execution.exception.DriverClosedException: Driver test Closed / Could not be reached
	at com.cognizant.cognizantits.engine.drivers.SeleniumDriver.isAlive(SeleniumDriver.java:143)
	at com.cognizant.cognizantits.engine.core.CommandControl.canIFindElement(CommandControl.java:103)
	at com.cognizant.cognizantits.engine.core.CommandControl.sync(CommandControl.java:92)
	at com.cognizant.cognizantits.engine.core.CommandControl.sync(CommandControl.java:170)
	at com.cognizant.cognizantits.engine.execution.run.TestStepRunner.executeStep(TestStepRunner.java:143)
	at com.cognizant.cognizantits.engine.execution.run.TestStepRunner.executeStep(TestStepRunner.java:132)
	at com.cognizant.cognizantits.engine.execution.run.TestStepRunner.run(TestStepRunner.java:60)
	at com.cognizant.cognizantits.engine.execution.run.TestCaseRunner.runStep(TestCaseRunner.java:376)
	at com.cognizant.cognizantits.engine.execution.run.TestCaseRunner.run(TestCaseRunner.java:334)
	at com.cognizant.cognizantits.engine.core.Task.runIteration(Task.java:123)
	at com.cognizant.cognizantits.engine.core.Task.run(Task.java:79)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

[console.txt](https://github.com/CognizantQAHub/Cognizant-Intelligent-Test-Scripter/files/1148174/console.txt)

**Comment by phystem** [comment]
This is caused due to Pull Request #5 - Commit 8883fd1

To check the if the driver is alive before each step checked for `driver.getCurrentUrl()`. But it is not applicable to Native Automation using Appium. Appium throws exception abruptly closes the driver.

**Comment by Shantha93** [comment]
This works with no issues after the hot fix.
