### ISSUE TITLE
Firefox not launching when run in debug mode from UI

### ISSUE THREAD

**Issue by phystem** [CognizantQAHub/Cognizant-Intelligent-Test-Scripter#7]
When Chrome/Firefox is launched in debug mode, the respective extensions for them are added via Selenium Capabilities.

But for firefox it is throwing the below exception

```
Caused by: org.openqa.selenium.WebDriverException: java.io.FileNotFoundException: C:\Users\user\AppData\Local\Temp\unzip5006317497018973935stream\install.rdf (The system cannot find the file specified)
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'DESKTOP-308IKTK', ip: '10.0.0.124', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.firefox.internal.FileExtension.readIdFromInstallRdf(FileExtension.java:142)
	at org.openqa.selenium.firefox.internal.FileExtension.writeTo(FileExtension.java:61)
	at org.openqa.selenium.firefox.FirefoxProfile.installExtensions(FirefoxProfile.java:424)
	at org.openqa.selenium.firefox.FirefoxProfile.layoutOnDisk(FirefoxProfile.java:402)
	at org.openqa.selenium.firefox.FirefoxProfile.toJson(FirefoxProfile.java:374)
	at org.openqa.selenium.firefox.FirefoxOptions.toJson(FirefoxOptions.java:557)
	... 40 more
Caused by: java.io.FileNotFoundException: C:\Users\user\AppData\Local\Temp\unzip5006317497018973935stream\install.rdf (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
	at org.apache.xerces.impl.XMLEntityManager.setupCurrentEntity(Unknown Source)
	at org.apache.xerces.impl.XMLVersionDetector.determineDocVersion(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:205)
	at org.openqa.selenium.firefox.internal.FileExtension.readIdFromInstallRdf(FileExtension.java:98)
	... 45 more

```

It's a bug with FirefoxDriver/GeckoDriver and is raised in respective forums.

https://github.com/SeleniumHQ/selenium/issues/4184

https://github.com/mozilla/geckodriver/issues/759.

**Comment by phystem** [comment]
#39  workaround has been done as of now.
